config/routes.rb
Rails.application.routes.draw do

  get '/science' => 'static_pages#science'
  get '/about' => 'static_pages#about'

  devise_for :users
  get 'foods/autocomplete_food_name'
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'
  get 'carts/checkout'

  resources :foods

  resource :cart, only: [:show ,:checkout]
  resources :cart_items, only: [:create, :update, :destroy]
  root to: "foods#index"

end

app/models/food.rb
class Food < ActiveRecord::Base
	has_many :contents
	has_many :cart_items
	
scope :name_like, -> (name) { where("name ilike ?", name)}
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  #before_action :set_food, only: [:show, :edit, :update, :destroy]
  autocomplete :food, :name, :full => false
  # GET /foods
  # GET /foods.json
  def index

  @foods = Food.all.page(params[:page]).per(1)
      if params[:search]
        @foods = Food.name_like("%#{params[:search]}%").order('name').page(params[:page]).per(10)
      else
      end

    @cart_item = current_cart.cart_items.new
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :serve_size)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<tr>
<td>
    <div class="col-md-8 ">
      <h4><%= food.name %></small></h4>

      <h4><strong>Serving Size</strong> <%= food.serve_size %></small></h4>
    </div>
    <div class="col-md-4">
      
      <%= form_for @cart_item, remote: true do |f| %>
      <div class="row">
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :food_id, value: food.id %>
            <%= f.submit "Add to Plate", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    </td>
</tr>

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :serve_size %><br>
    <%= f.text_field :serve_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/_search_results.html.erb
<table class="table table-striped table-hover ">
  <tbody>

       </thead>
			<tbody id="results">
			
				<%= render @foods %>

			</tbody>
		</table>
		<div id="paginator">
			<%= paginate @foods, :remote => true %>
		</div>
    

</tbody>
</table>
 	

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<!--cart counter-->
<div id="fixedbutton" data-step="3" data-intro="When finished, click here!" >
<div class="cart-text"><%= render 'layouts/cart_text' %></div>
</div>
<!---->



<div class="jumbotron" style="background-image: url(<%= asset_path "splash.jpg" %>);">
<div class="well well-sm" id="splash-well">
<h2 class="splashtext">IS YOUR DIET GIVING YOU RICKETS?</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<h4 class="splashtext">Weight loss should not come at the expense of vitamin and mineral deficiency. Diet Rater gives you the tools to analyze the micronutrient content of any diet.</h4>
</div>
</div>
<h3 class="splashtext">Save your bones, rate your diet.</h2>
</div>
<div class="splashtext">
<a id="startButton" class="btn btn-large btn-success" href="javascript:void(0);">Show me how</a>
</div>
</div>


<h3 class="text-center">Add some foods to your plate for analysis</h3>
<div class ="row">
<div class ="col-md-8 col-md-offset-2">
<div class ="well well-sm" align="center" data-step="1" data-intro="Find some foods you eat from our database" data-position="top">



<%= form_tag(foods_path, :method => "get", id: "search-form", remote:true  )  do %>
<!-- text field tag=action,args,identifier,placeholdertext... -->
<%= text_field_tag :search, params[:search], class: "search-query", placeholder: "Search food by name", type: "search", data: {autocomplete: foods_autocomplete_food_name_path}, :size=>"50"  %>  
<%= submit_tag "Search" %>
<%end%>
<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('#search-form').submit()
  });
</script>



</div>
</div>
</div>
<hr>


<div class="row">
  <div class="col-md-8 col-md-offset-2" data-step="2" data-intro="Add foods to your plate" data-position="top">

<div id="results">
  <%= render :partial => 'search_results'%>
</div>

  </div>
</div>

<script type="text/javascript">
  document.getElementById('startButton').onclick = function() {
    introJs().setOption('doneLabel', 'Next page').start().oncomplete(function() {
      window.location.href = '/cart?multipage=true';
    });
  };
</script>

app/views/foods/index.js.erb
$('tbody#results').html('<%= escape_javascript render(@foods) %>');

$('#paginator').html('<%= escape_javascript(paginate(@foods, :remote => true).to_s) %>');

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Serve size:</strong>
  <%= @food.serve_size %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>