config/routes.rb
Rails.application.routes.draw do

  get '/science' => 'static_pages#science'
  get '/about' => 'static_pages#about'

  devise_for :users
  get 'foods/autocomplete_food_name'
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'
  get 'carts/checkout'

  resources :foods

  resource :cart, only: [:show ,:checkout]
  resources :cart_items, only: [:create, :update, :destroy]
  root to: "foods#index"

end

app/views/layouts/_cart_text.html.erb
<%= link_to cart_path, class: "btn btn-success active"   do %>
<i class="fa fa-bar-chart"></i>	Analyze plate of
<br>
<%="#{current_cart.cart_items.size} dishes" %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diet Rater</title>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <% if request.ssl? %>
    <!-- <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %> -->
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
<!--     <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %> -->
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">


<div id="top-nav">


    <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="logo-holder"><a href="/" class="navbar-brand"><%= image_tag 'logo.png',size:"150x70"%></a></div>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/science">The Science</a></li>
                <li><a href="/about">About Us</a></li>
            </ul>
        </div>
    </nav>
</div>
</div>


  

    <%= yield %>


</body>




<footer>


  <p align="center">A Rails Experiement by Yifei Wu. <a href="https://github.com/yifeiwu">
  Github</a>.</p>

</footer>
</html>